### ISSUE TITLE
use auto-js-ipfs for IPFS loading/uploading

### ISSUE THREAD

**Issue by RangerMauve** [webrecorder/web-replay-gen#25]
https://github.com/RangerMauve/auto-js-ipfs

This will likely be covered when [wabac.js](https://github.com/webrecorder/wabac.js/issues/80) is updated.

**Comment by ikreymer** [comment]
Leaving as placeholder, as we may not have much to do here, given #11 for documentation, and webrecorder/wabac.js#80 :) 

I *think* we may actually not need auto-js-ipfs here, as we'll just pass `ipfs://` urls directly to <replay-web-page> and it should just work!

**Comment by ikreymer** [comment]
With release of replayweb.page 1.7.0, this is implemented, no work to be done in this repo.
