### ISSUE TITLE
Support 'SPA Mode' with archives.json-based config.

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/web-replay-gen#30]
Have an option where the the archives.js is instead an archives.json, and the entire site can be loaded as an SPA?

This should then have all of the settings, such as title, also be loaded form archives.json

Perhaps this would also disable sitemap.xml generation and anything else that requires a separate page.

Can we support both current mode and SPA-mode with simple toggle?

This would allow taking an existing published site as a template, and simply replacing `archives.json` to get a new site, and publishing to a new static site (eg. on IPFS).

**Comment by SuaYoo** [comment]
Moving towards paradigm where entire site is configured at runtime with JSON
