### ISSUE TITLE
github action fails when creating new project

### ISSUE THREAD

**Issue by evanwill** [webrecorder/web-replay-gen#44]
Not sure if this is related to #34 but if following the steps currently listed in the Readme, when a user creates a new repository using the template, the included GitHub Action [workflow file](https://github.com/webrecorder/web-replay-gen/blob/main/.github/workflows/publish-gh-pages.yml) will immediately run and end with a build error. The error is because GitHub Pages is not activated in the new repository, so the build step can't finish the deploy. 

To successfully build/deploy, the user must go to their "Settings" > "Pages" for the new repository, and under "Source" select "GitHub Actions". Then trigger a new build (either manually or via a new commit). 

Since getting the Action error is confusing, it would be helpful to document the solution, or alternatively remove the workflow file and provide documentation on how to add it to the repository after creation. 

Thank you for your work on this project! Very interesting.

**Comment by tw4l** [comment]
@evanwill thanks for the heads up, and apologies for the slow response! I've opened a PR to document this extra step in the README.
